package ir.masoud.yadgoo;

import android.Manifest;import android.app.*;import android.os.*;import android.content.*;import android.graphics.Color;import android.speech.*;import android.view.*;import android.widget.*;import org.json.*;import java.util.*;import java.text.*;

public class MainActivity extends Activity {
 LinearLayout root,list; EditText input; Spinner section; JSONArray items; int tab=0; final String[] tabs={"امروز","صندوق","کارها","پروژه‌ها","جست‌وجو"};
 int ink=Color.rgb(23,34,59),blue=Color.rgb(46,91,211); SpeechRecognizer recognizer;
 public void onCreate(Bundle b){super.onCreate(b);getWindow().setStatusBarColor(ink);getWindow().setNavigationBarColor(ink);load();show();}
 void load(){try{items=new JSONArray(getPreferences(0).getString("items","[]"));}catch(Exception e){items=new JSONArray();}}
 void save(){getPreferences(0).edit().putString("items",items.toString()).apply();}
 TextView text(String s,int size){TextView t=new TextView(this);t.setText(s);t.setTextSize(size);t.setTextColor(ink);t.setGravity(Gravity.RIGHT);t.setPadding(18,14,18,14);return t;}
 void show(){root=new LinearLayout(this);root.setOrientation(1);root.setBackgroundColor(Color.rgb(246,248,253));root.setLayoutDirection(View.LAYOUT_DIRECTION_RTL);setContentView(root);
 TextView head=text("یادگو  •  دستیار کارهای من",23);head.setTextColor(Color.WHITE);head.setBackgroundColor(ink);root.addView(head);
 HorizontalScrollView hs=new HorizontalScrollView(this);LinearLayout nav=new LinearLayout(this);for(int j=0;j<tabs.length;j++){final int k=j;Button b=new Button(this);b.setText(tabs[j]);b.setAllCaps(false);b.setOnClickListener(v->{tab=k;show();});nav.addView(b);}hs.addView(nav);root.addView(hs);
 if(tab!=4){Button mic=new Button(this);mic.setText("🎙  بگو چی یادت نره");mic.setTextColor(Color.WHITE);mic.setBackgroundTintList(android.content.res.ColorStateList.valueOf(blue));mic.setOnClickListener(v->listen());root.addView(mic);
 input=new EditText(this);input.setHint("یا اینجا بنویس…");input.setSingleLine(false);input.setMinLines(2);root.addView(input);
 section=new Spinner(this);String[] cats={"تشخیص خودکار","کار / انبار","شخصی","خانه","سایت","ذکران","مدیر مالی من"};ArrayAdapter<String> a=new ArrayAdapter<>(this,android.R.layout.simple_spinner_dropdown_item,cats);section.setAdapter(a);root.addView(section);
 Button add=new Button(this);add.setText("ذخیره یادداشت یا کار");add.setOnClickListener(v->add(input.getText().toString()));root.addView(add);
 }else{input=new EditText(this);input.setHint("جست‌وجو در یادداشت‌ها و پروژه‌ها");root.addView(input);input.addTextChangedListener(new android.text.TextWatcher(){public void beforeTextChanged(CharSequence s,int st,int c,int af){}public void onTextChanged(CharSequence s,int st,int before,int count){render();}public void afterTextChanged(android.text.Editable e){}});}
 ScrollView sc=new ScrollView(this);list=new LinearLayout(this);list.setOrientation(1);sc.addView(list);root.addView(sc,new LinearLayout.LayoutParams(-1,0,1));render();}
 void listen(){if(!SpeechRecognizer.isRecognitionAvailable(this)){toast("سرویس تشخیص گفتار روی این گوشی فعال نیست؛ می‌توانید تایپ کنید");return;} if(checkSelfPermission(Manifest.permission.RECORD_AUDIO)!=getPackageManager().PERMISSION_GRANTED){requestPermissions(new String[]{Manifest.permission.RECORD_AUDIO},7);return;} if(recognizer!=null)recognizer.destroy();recognizer=SpeechRecognizer.createSpeechRecognizer(this);recognizer.setRecognitionListener(new RecognitionListener(){public void onReadyForSpeech(Bundle p){toast("گوش می‌کنم…");}public void onBeginningOfSpeech(){}public void onRmsChanged(float v){}public void onBufferReceived(byte[] b){}public void onEndOfSpeech(){}public void onError(int e){toast("گفتار دریافت نشد؛ دوباره امتحان کنید");}public void onResults(Bundle b){ArrayList<String> a=b.getStringArrayList(SpeechRecognizer.RESULTS_RECOGNITION);if(a!=null&&!a.isEmpty())input.setText(a.get(0));}public void onPartialResults(Bundle b){}public void onEvent(int e,Bundle b){}});Intent i=new Intent(RecognizerIntent.ACTION_RECOGNIZE_SPEECH);i.putExtra(RecognizerIntent.EXTRA_LANGUAGE,"fa-IR");i.putExtra(RecognizerIntent.EXTRA_LANGUAGE_MODEL,RecognizerIntent.LANGUAGE_MODEL_FREE_FORM);recognizer.startListening(i);}
 String classify(String s){if(section!=null&&section.getSelectedItemPosition()>0)return section.getSelectedItem().toString();if(s.contains("ذکران")||s.contains("آیت الکرسی")||s.contains("تقویم"))return "ذکران";if(s.contains("سایت")||s.contains("صفحه پروژه"))return "سایت";if(s.contains("مدیریت مالی")||s.contains("اقساط"))return "مدیر مالی من";if(s.contains("انبار")||s.contains("کارخانه")||s.contains("موجودی")||s.contains("پیمانکار"))return "کار / انبار";if(s.contains("خانه")||s.contains("خرید"))return "خانه";return "شخصی";}
 long due(String s){Calendar c=Calendar.getInstance();boolean tomorrow=s.contains("فردا")||s.contains("یک روز فرصت")||s.contains("یه روز فرصت");if(tomorrow)c.add(Calendar.DATE,1);else if(!s.contains("امروز"))return 0;java.util.regex.Matcher m=java.util.regex.Pattern.compile("ساعت\\s*([۰-۹0-9]{1,2})(?:[:：]([۰-۹0-9]{1,2}))?").matcher(s);int hour=9,min=0;if(m.find()){hour=Integer.parseInt(fa2en(m.group(1)));if(m.group(2)!=null)min=Integer.parseInt(fa2en(m.group(2)));}if(hour>23||min>59)return 0;c.set(Calendar.HOUR_OF_DAY,hour);c.set(Calendar.MINUTE,min);c.set(Calendar.SECOND,0);return c.getTimeInMillis();}
 String fa2en(String s){return s.replace('۰','0').replace('۱','1').replace('۲','2').replace('۳','3').replace('۴','4').replace('۵','5').replace('۶','6').replace('۷','7').replace('۸','8').replace('۹','9');}
 void add(String s){s=s.trim();if(s.isEmpty()){toast("متن را وارد کنید");return;}try{JSONObject o=new JSONObject();o.put("id",System.currentTimeMillis());o.put("text",s);o.put("category",classify(s));o.put("due",due(s));o.put("done",false);o.put("created",System.currentTimeMillis());items.put(o);save();if(o.getLong("due")>System.currentTimeMillis())remind(o);toast("ذخیره شد");show();}catch(Exception e){toast("ذخیره نشد");}}
 void remind(JSONObject o){try{if(Build.VERSION.SDK_INT>=33&&checkSelfPermission(Manifest.permission.POST_NOTIFICATIONS)!=getPackageManager().PERMISSION_GRANTED)requestPermissions(new String[]{Manifest.permission.POST_NOTIFICATIONS},8);Intent i=new Intent(this,ReminderReceiver.class);i.putExtra("title",o.getString("text"));int id=(int)(o.getLong("id")%Integer.MAX_VALUE);i.putExtra("id",id);PendingIntent p=PendingIntent.getBroadcast(this,id,i,PendingIntent.FLAG_UPDATE_CURRENT|PendingIntent.FLAG_IMMUTABLE);AlarmManager a=getSystemService(AlarmManager.class);long when=o.getLong("due");if(Build.VERSION.SDK_INT>=31&&a.canScheduleExactAlarms())a.setExactAndAllowWhileIdle(AlarmManager.RTC_WAKEUP,when,p);else a.setAndAllowWhileIdle(AlarmManager.RTC_WAKEUP,when,p);}catch(Exception e){toast("ثبت شد؛ زمان اعلان را در تنظیمات گوشی بررسی کنید");}}
 void render(){if(list==null)return;list.removeAllViews();long now=System.currentTimeMillis();String query=tab==4?input.getText().toString().trim():"";int count=0;for(int j=items.length()-1;j>=0;j--){JSONObject o=items.optJSONObject(j);if(o==null)continue;String s=o.optString("text"),cat=o.optString("category");long d=o.optLong("due");boolean done=o.optBoolean("done");if(tab==0&&(done||d==0||d>now+86400000L))continue;if(tab==1&&(done||d!=0))continue;if(tab==2&&(done||d==0))continue;if(tab==3&&!Arrays.asList("سایت","ذکران","مدیر مالی من").contains(cat))continue;if(tab==4&&!s.contains(query)&&!cat.contains(query))continue;count++;final int index=j;LinearLayout card=new LinearLayout(this);card.setOrientation(1);card.setPadding(12,8,12,8);card.setBackgroundColor(Color.WHITE);LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,-2);lp.setMargins(12,7,12,7);list.addView(card,lp);TextView title=text(s,17);card.addView(title);String subtitle=cat+(d>0?"  •  "+new SimpleDateFormat("yyyy/MM/dd HH:mm",Locale.getDefault()).format(new Date(d)):"  •  بدون موعد")+(done?"  •  انجام شد":"");TextView meta=text(subtitle,12);meta.setTextColor(blue);card.addView(meta);LinearLayout actions=new LinearLayout(this);Button finish=new Button(this);finish.setText(done?"بازگشایی":"انجام شد");finish.setOnClickListener(v->{try{o.put("done",!done);save();render();}catch(Exception ignored){}});actions.addView(finish);Button edit=new Button(this);edit.setText("ویرایش");edit.setOnClickListener(v->{EditText e=new EditText(this);e.setText(s);new AlertDialog.Builder(this).setTitle("ویرایش متن").setView(e).setPositiveButton("ذخیره",(a,b)->{try{o.put("text",e.getText().toString());save();render();}catch(Exception ignored){}}).setNegativeButton("انصراف",null).show();});actions.addView(edit);Button del=new Button(this);del.setText("حذف");del.setOnClickListener(v->new AlertDialog.Builder(this).setMessage("این مورد حذف شود؟").setPositiveButton("حذف",(a,b)->{JSONArray replacement=new JSONArray();for(int x=0;x<items.length();x++)if(x!=index)replacement.put(items.opt(x));items=replacement;save();render();}).setNegativeButton("انصراف",null).show());actions.addView(del);card.addView(actions);}if(count==0)list.addView(text("موردی برای نمایش نیست.",16));}
 void toast(String s){Toast.makeText(this,s,Toast.LENGTH_SHORT).show();}protected void onDestroy(){if(recognizer!=null)recognizer.destroy();super.onDestroy();}
}
